package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Thursday, May 11, 2023 4:02:12 PM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
